services:
  # app services
  api:
    image: weather-forecast-api
    build:
      context: ./apps/api
      args:
        - service=api
    env_file:
      - ./apps/api/.env
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/weather-forecast
      - PORT=8080
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    restart: "always"
    links:
      - mongodb

  ui:
    image: weather-forecast-ui
    build:
      context: ./apps/ui
    ports:
      - 80:80
    depends_on:
      - api

  # Dependencies
  mongodb:
    image: mongo:6
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data_container:
networks:
  node-network:
    driver: bridge
# docker compose up -d
# docker compose up -d --build
# docker compose down
