name: CI

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ["1.23.x"]
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      # Setup go
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      # Set up node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: apps/ui/package-lock.json

      # install and build
      - run: make install_all
      - run: make test_all
      - run: make build_all

  build-image:
    name: build-image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: touch ./apps/timer/.env
      - run: docker compose -f docker-compose.yml build
